# Generated by Django 3.0.5 on 2020-04-29 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='travel_time',
            new_name='traveling_time',
        ),
    ]
